# Generated by Django 5.2.6 on 2025-11-16 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'male'), ('F', 'female')], max_length=1, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('dob', models.DateField(auto_now_add=True, null=True)),
                ('state', models.CharField(blank=True, choices=[('K', 'KERALA'), ('J&K', 'JAMMU&KASHMIR'), ('P', 'PUNJAB')], max_length=3, null=True)),
                ('district', models.CharField(blank=True, choices=[('T', 'THIRUVANANTHAPURAM'), ('K', 'KOLLAM'), ('P', 'PATHANAMTHITTA'), ('A', 'ALAPPUZHA'), ('K', 'KOTTAYAM'), ('I', 'IDUKKI'), ('E', 'ERANAMKULAM'), ('TH', 'THRISSUR'), ('P', 'PALAKKAD'), ('M', 'MALAPPURAM'), ('KH', 'KOZHIKODE'), ('W', 'WAYANAD'), ('KA', 'KANNUR'), ('KS', 'KASARGOD')], max_length=5, null=True)),
            ],
        ),
    ]
