# Generated by Django 5.2.6 on 2025-11-23 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillsharingapp', '0002_user_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'male'), ('F', 'female')], max_length=1, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('dob', models.DateField(auto_now_add=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='teacherimages/')),
                ('state', models.CharField(blank=True, choices=[('K', 'KERALA'), ('J&K', 'JAMMU&KASHMIR'), ('P', 'PUNJAB')], max_length=3, null=True)),
                ('district', models.CharField(blank=True, choices=[('T', 'THIRUVANANTHAPURAM'), ('K', 'KOLLAM'), ('P', 'PATHANAMTHITTA'), ('A', 'ALAPPUZHA'), ('K', 'KOTTAYAM'), ('I', 'IDUKKI'), ('E', 'ERANAMKULAM'), ('TH', 'THRISSUR'), ('P', 'PALAKKAD'), ('M', 'MALAPPURAM'), ('KH', 'KOZHIKODE'), ('W', 'WAYANAD'), ('KA', 'KANNUR'), ('KS', 'KASARGOD')], max_length=5, null=True)),
                ('qualification', models.CharField(blank=True, choices=[('BA', 'Bachelor of Arts'), ('BFA', 'Bachelor of Fine Arts'), ('BDes', 'Bachelor of Design'), ('BJMC', 'Bachelor of Journalism & Mass Communication')], max_length=5, null=True)),
                ('experience', models.IntegerField(blank=True, null=True)),
                ('certificate', models.ImageField(blank=True, null=True, upload_to='certificate/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
