# Generated by Django 5.2.6 on 2025-11-24 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillsharingapp', '0003_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='status',
        ),
        migrations.AddField(
            model_name='teacher',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='experience',
            field=models.IntegerField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='qualification',
            field=models.CharField(blank=True, choices=[('BA', 'Bachelor of Arts'), ('BFA', 'Bachelor of Fine Arts'), ('BDes', 'Bachelor of Design'), ('BJMC', 'Bachelor of Journalism & Mass Communication')], max_length=4, null=True),
        ),
    ]
