# Generated by Django 5.2.6 on 2025-11-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillsharingapp', '0004_remove_teacher_created_at_remove_teacher_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='experience',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
