# Generated by Django 5.2.8 on 2025-11-25 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillsharingapp', '0006_teacher_created_at_alter_teacher_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='teacher',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
