# Generated by Django 5.2.8 on 2025-11-25 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillsharingapp', '0007_remove_teacher_is_approved_teacher_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='approved_at',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='district',
            field=models.CharField(blank=True, choices=[('THIRUVANANTHAPURAM', 'THIRUVANANTHAPURAM'), ('KOLLAM', 'KOLLAM'), ('PATHANAMTHITTA', 'PATHANAMTHITTA'), ('ALAPPUZHA', 'ALAPPUZHA'), ('KOTTAYAM', 'KOTTAYAM'), ('IDUKKI', 'IDUKKI'), ('ERANAMKULAM', 'ERANAMKULAM'), ('THRISSUR', 'THRISSUR'), ('PALAKKAD', 'PALAKKAD'), ('MALAPPURAM', 'MALAPPURAM'), ('KOZHIKODE', 'KOZHIKODE'), ('WAYANAD', 'WAYANAD'), ('KANNUR', 'KANNUR'), ('KASARGOD', 'KASARGOD')], null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='state',
            field=models.CharField(blank=True, choices=[('KERALA', 'KERALA'), ('JAMMU&KASHMIR', 'JAMMU&KASHMIR'), ('PUNJAB', 'PUNJAB')], null=True),
        ),
    ]
