# Generated by Django 5.2.8 on 2025-11-25 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillsharingapp', '0008_remove_teacher_approved_at_alter_teacher_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female')], null=True),
        ),
    ]
