# Generated by Django 5.2.8 on 2025-11-25 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillsharingapp', '0009_alter_teacher_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload_Offline_Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='video/')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('useremail', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Upload_Online_Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('link', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('useremail', models.CharField(blank=True, max_length=255, null=True)),
                ('instructor', models.CharField(blank=True, max_length=100, null=True)),
                ('duration', models.TimeField(blank=True, null=True)),
                ('platform', models.CharField(blank=True, choices=[('Google Meet', 'Google Meet'), ('Zoom', 'Zoom'), ('Microsoft Teams', 'Microsoft Teams'), ('Other', 'Other')], null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('materials', models.FileField(blank=True, null=True, upload_to='materials/')),
            ],
        ),
    ]
