# Generated by Django 5.2.8 on 2025-11-25 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillsharingapp', '0010_upload_offline_class_upload_online_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload_online_class',
            name='duration',
            field=models.CharField(blank=True, null=True),
        ),
    ]
