# Generated by Django 5.2.8 on 2025-11-28 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillsharingapp', '0011_alter_upload_online_class_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='isapproved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacher',
            name='isrejected',
            field=models.BooleanField(default=False),
        ),
    ]
