# Generated by Django 5.2.6 on 2025-12-13 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillsharingapp', '0014_teacher_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.CharField(blank=True, choices=[('Drawing', 'Drawing'), ('Dancing', 'Dancing'), ('Singing', 'Singing'), ('Painting', 'Painting'), ('Origami', 'Origami'), ('Arts', 'Arts')], max_length=10, null=True),
        ),
    ]
