# Generated by Django 5.2.7 on 2026-01-09 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillsharingapp', '0017_remove_course_skill_tag_remove_course_video_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='skill_tag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='course_videos/'),
        ),
    ]
