# Generated by Django 5.2.9 on 2026-01-09 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillsharingapp', '0019_remove_enrollment_is_paid_enrollment_enrolled_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('institute_type', models.CharField(choices=[('it_training', 'IT Training'), ('arts_science', 'Arts & Science College'), ('polytechnic', 'Polytechnic'), ('skill_training', 'Skill Training'), ('coaching', 'Coaching Center'), ('other', 'Other')], max_length=50)),
                ('registration_certificate', models.FileField(upload_to='certificates/')),
                ('password', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
