# Generated by Django 5.2.9 on 2026-01-09 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillsharingapp', '0020_institute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='institute',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='skillsharingapp.institute'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
    ]
