# Generated by Django 5.2.9 on 2026-01-09 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skillsharingapp', '0021_alter_course_institute_delete_enrollment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.DeleteModel(
            name='Upload_Offline_Class',
        ),
        migrations.DeleteModel(
            name='Upload_Online_Class',
        ),
    ]
