# Generated by Django 5.2.9 on 2026-01-09 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skillsharingapp', '0022_delete_teacher_delete_upload_offline_class_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Student',
        ),
    ]
