# Generated by Django 5.2.9 on 2026-01-09 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillsharingapp', '0023_rename_user_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='skillsets',
            field=models.TextField(blank=True, null=True),
        ),
    ]
