# Generated by Django 5.2.10 on 2026-01-10 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillsharingapp', '0025_coursepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='confirm_password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
